import { MenuItem, JukeboxTrack } from './types';

export const CATEGORIES = [
  { id: 'all', label: 'Semua Menu', icon: 'Sparkles' },
  { id: 'coffee', label: 'Coffee', icon: 'Coffee' },
  { id: 'non-coffee', label: 'Non-Coffee', icon: 'Milk' },
  { id: 'food', label: 'Main Course', icon: 'Utensils' },
  { id: 'dessert', label: 'Pastry & Dessert', icon: 'CakeSlice' },
] as const;

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'm1',
    name: 'Es Kopi Susu Aren Klasik',
    description: 'Espresso blend Arabika-Robusta dengan susu segar premium dan pemanis sirup gula aren lokal organik alami.',
    price: 28000,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    isPopular: true,
  },
  {
    id: 'm2',
    name: 'Manual Brew V60 Gayo',
    description: 'Kopi single-origin Gayo Aceh berpencar notes buah peach, citrus segar, dan teh melati yang aromatik.',
    price: 32000,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
  },
  {
    id: 'm3',
    name: 'Iced Rose Matcha Latte',
    description: 'Perpaduan bubuk matcha Kyoto grade-A murni dengan susu segar berpemanis madu murni dan sirup ekstrak bunga mawar.',
    price: 35000,
    category: 'non-coffee',
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
    isPopular: true,
  },
  {
    id: 'm4',
    name: 'Avocado Cold Brew Milkshake',
    description: 'Jus alpukat mentega segar diblender kental dengan es, espresso cold brew, dan topping es krim vanila lembut.',
    price: 38000,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=600&q=80',
    rating: 4.6,
  },
  {
    id: 'm5',
    name: 'Salted Caramel Hazelnut',
    description: 'Espresso double-shot dengan sirup caramel asin buatan sendiri, aroma kemiri panggang, dan creamy foam melimpah.',
    price: 36000,
    category: 'coffee',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    isPopular: true,
  },
  {
    id: 'm6',
    name: 'Lychee Spring Tea Refresh',
    description: 'Seduhan teh premium Oolong dingin yang dikocok bersama buah leci manis asli, selasih, dan daun mint segar.',
    price: 26000,
    category: 'non-coffee',
    image: 'https://images.unsplash.com/photo-1497515114629-f71d768fd07c?auto=format&fit=crop&w=600&q=80',
    rating: 4.5,
  },
  {
    id: 'm7',
    name: 'Nasi Goreng Wagyu Kecombrang',
    description: 'Nasi goreng aromatik dengan irisan bunga kecombrang wangi, potongan daging sapi Wagyu premium empuk, telur mata sapi dan emping melinjo.',
    price: 65000,
    category: 'food',
    image: 'https://images.unsplash.com/photo-1603133872878-6966b46179c5?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    isPopular: true,
  },
  {
    id: 'm8',
    name: 'Spaghetti Aglio Olio Salmon',
    description: 'Pasta al dente ditumis minyak zaitun murni, cabai kering cincang, bawang putih renyah, dan dipanggang matang bersama potongan Salmon segar.',
    price: 58000,
    category: 'food',
    image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
  },
  {
    id: 'm9',
    name: 'Almond Cripsy Croissant',
    description: 'Butter croissant berlapis renyah luar biasa, diisi melimpah krim almond aromatik, dan taburan kacang garing serta gula bubuk es.',
    price: 29000,
    category: 'dessert',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80',
    rating: 4.7,
  },
  {
    id: 'm10',
    name: 'Classic Tiramisu Melt',
    description: 'Layer biskuit ladyfinger yang direndam espresso espresso pekat, keju mascarpone impor manis ringan, dan bubuk cokelat hitam premium.',
    price: 42000,
    category: 'dessert',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    isPopular: true,
  }
];

export const INITIAL_JUKEBOX: JukeboxTrack[] = [];